apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-0d66769406ab119bc
  capacity:
    storage: 20Gi